# Generated by Django 3.1.3 on 2020-11-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20201103_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
