# Generated by Django 3.1.3 on 2020-11-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20201105_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Masculino'), (1, 'Feminino')]),
        ),
    ]
