# Generated by Django 3.1.3 on 2020-11-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20201105_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
