# Generated by Django 3.1.3 on 2020-11-06 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast', to='movies.movie'),
        ),
    ]
